### ISSUE TITLE
Import/Export course/unit/...

### ISSUE THREAD

**Issue by utetrapp** [utetrapp/geli#42] opened 2017-05-01 11:38 UTC
# User Story

### As a: 
teacher

### I want:
import parts of a lecture to a new course

### so that:
reuse existing stuff in another course or be able to start a new course in a new semester based on an existing course.

## Acceptance criteria:
- [ ] Create a new course based on an existing course, unselect some units, copy all selected units into the just created course.
- [ ] Within an existing course import/copy units from another course. 

## Additional info:
extends #183 

## Estimated:
- 4 x 4hr

**Comment by d89** [comment] 2017-11-28 19:50
When exporting, this happens (for the shown test course):

![image](https://user-images.githubusercontent.com/423154/33340877-9127d4fa-d47d-11e7-9a70-94aa9a36e488.png)

`{"name":"TypeError","message":"Cannot read property 'exportJSON' of null","stack":"TypeError: Cannot read property 'exportJSON' of null\n    at Unit_1.Unit.findById.then (/usr/src/app/models/Lecture.js:61:29)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"}`

When duplicating, this happens:

![image](https://user-images.githubusercontent.com/423154/33340940-b3d44a92-d47d-11e7-89b4-9ca5c5f75783.png)

`{"name":"InternalServerError","message":"Failed to duplicate course","stack":"Error\n    at InternalServerError.HttpError [as constructor] (/usr/src/app/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at new InternalServerError (/usr/src/app/node_modules/routing-controllers/http-error/InternalServerError.js:20:28)\n    at DuplicationController.<anonymous> (/usr/src/app/controllers/DuplicationController.js:39:34)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/controllers/DuplicationController.js:17:65)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)\nCaused by: Cannot read property 'exportJSON' of null\nTypeError: Cannot read property 'exportJSON' of null\n    at Unit_1.Unit.findById.then (/usr/src/app/models/Lecture.js:61:29)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"}`

**Comment by khase** [comment] 2017-11-28 21:44
okay, just figured out the reason for this error. this Course contains some lectures which didn't got deleted cleanly.

Chould be the same error for https://github.com/h-da/geli/issues/183

**Comment by d89** [comment] 2017-12-04 18:53
Added criteria in the session on 2017-11-30:

- [ ] Remove enroll key, whitelist and "active" flag in the export

**Comment by lukaskorte** [comment] 2018-01-03 19:51
Closed by #419

**Comment by d89** [comment] 2018-01-21 20:31
Still can't download the FWE course (https://staging.geli.fbi.h-da.de/course/597df6d5b7a9c0000616637f):

The error is the following:

![image](https://user-images.githubusercontent.com/423154/35198626-b812045c-fef1-11e7-96ea-3a862c1fe13f.png)

When I try to imort the course https://staging.geli.fbi.h-da.de/course/59fa100662fa9c00060bb3d2 (which I previously exported to the following JSON file, I get an error).

[Dritter-Kurs-von-David.json.log](https://github.com/h-da/geli/files/1650175/Dritter-Kurs-von-David.json.log)

`{"name":"InternalServerError","message":"Failed to import course","stack":"Error\n    at InternalServerError.HttpError [as constructor] (/usr/src/app/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at new InternalServerError (/usr/src/app/node_modules/routing-controllers/http-error/InternalServerError.js:20:28)\n    at Object.<anonymous> (/usr/src/app/models/Course.js:152:30)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/models/Course.js:5:65)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)\nCaused by: Failed to import lecture\nError\n    at InternalServerError.HttpError [as constructor] (/usr/src/app/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at new InternalServerError (/usr/src/app/node_modules/routing-controllers/http-error/InternalServerError.js:20:28)\n    at Object.<anonymous> (/usr/src/app/models/Lecture.js:92:30)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/models/Lecture.js:5:65)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)\nCaused by: Failed to import unit of type file\nError\n    at InternalServerError.HttpError [as constructor] (/usr/src/app/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at new InternalServerError (/usr/src/app/node_modules/routing-controllers/http-error/InternalServerError.js:20:28)\n    at Object.<anonymous> (/usr/src/app/models/units/Unit.js:82:30)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/models/units/Unit.js:5:65)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)\nCaused by: file validation failed: fileUnitType: Path `fileUnitType` is required.\nValidationError: file validation failed: fileUnitType: Path `fileUnitType` is required.\n    at new ValidationError (/usr/src/app/node_modules/mongoose/lib/error/validation.js:28:11)\n    at model.Document.invalidate (/usr/src/app/node_modules/mongoose/lib/document.js:1675:32)\n    at /usr/src/app/node_modules/mongoose/lib/document.js:1547:17\n    at validate (/usr/src/app/node_modules/mongoose/lib/schematype.js:784:7)\n    at /usr/src/app/node_modules/mongoose/lib/schematype.js:829:11\n    at Array.forEach (<anonymous>)\n    at SchemaString.SchemaType.doValidate (/usr/src/app/node_modules/mongoose/lib/schematype.js:789:19)\n    at /usr/src/app/node_modules/mongoose/lib/document.js:1545:9\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"}`

**Comment by HPunktOchs** [comment] 2018-06-14 09:56
Its the bsontype= "ObjectId" which leads to failures. This contains all Courses which have fileunits and all courses that contain references in the Mediamanager. Also, some Courses have leftover References in the "media" section (on export in the json) but none visible in the GUI.
Also, the concept of just referencing Media files seems a bit problmatic in some aspects. Maybe we shouldnt be able to export media-units for now. Or on Import, we should just create "empty" file units with description and the name as placeholder.

**Closed** 2018-06-24 19:29 UTC
Labels: enhancement, future
